### ISSUE TITLE
Compile failed - Multiple issues

### ISSUE THREAD

**Issue by christopherwk210** [GameMakerDiscord/GMEdit#11]
Just pulled the latest upstream, tried to compile with
```
$ haxe -cp src -js ./bin/resources/app/app.js -D nodejs -main Main -dce full
```
I received this error
```
src/tools/Dictionary.hx:11: characters 9-11 : Type not found : js.Object
src/tools/NativeObject.hx:13: characters 10-21 : Type not found : js.Function
/usr/local/lib/haxe/std/neko/_std/sys/io/File.hx:54: characters 32-84 : ../bin/buildnumber.txt: No such file or directory
/usr/local/lib/haxe/std/neko/_std/sys/io/File.hx:38: characters 10-21 : Called from
src/ace/AceMacro.hx:13: characters 2-56 : Called from
src/ui/WelcomePage.hx:13: characters 60-84 : Called from
Aborted
```
Maybe a missing import?

**Comment by YellowAfterlife** [comment]
Differences between stable and beta versions of Haxe - standard library was moved around. Might be worthwhile to migrate to [4.0.0 preview](https://haxe.org/download/version/4.0.0-preview.3/) so that I don't have to insert hacks that will only stick around for a bit.

**Comment by christopherwk210** [comment]
Gotcha! I updated haxe and ran the same command, this was the output:
```
src/ui/WelcomePage.hx:13: characters 61-85 : Uncaught exception Could not write file ../bin/buildnumber.txt
No stack information available, consider compiling with -D eval-stack
For function argument 'by'
src/ui/WelcomePage.hx:9: lines 9-18 : Defined in this class
```
tried creating an empty file of that name manually in the bin/ folder just to see if that would work, but no dice

**Comment by YellowAfterlife** [comment]
Can try changing that path in code to just "bin" instead of "../bin" - I do have project (and thus relative directory) inside "src" because FlashDevelop hangs briefly when trying to re-index Ace files.

**Comment by christopherwk210** [comment]
That worked for me, thanks 👍
