### ISSUE TITLE
Suggestion: snippets

### ISSUE THREAD

**Issue by maciekr1234** [GameMakerDiscord/GMEdit#15]
It would be nice to be able to use snippets in GMEdit. I found dirty way to enable Ace's built in snippet engine but I didn't manage to have them pop out in autocomplete (probably because you made your own autocomplete module). Anyway, it would be appreciate if you could implement them sometime.
Thanks :)

**Comment by YellowAfterlife** [comment]
Implemented for the next release and honestly this was way worse than it should have been - as far as I can tell, there's no documentation whatsoever on updating snippets after initial load.
