### ISSUE TITLE
Coroutines and multi-line comments

### ISSUE THREAD

**Issue by maciekr1234** [GameMakerDiscord/GMEdit#16]
When you have `#gmcr` + multi-line comment with single star `/* */` editor gives this error upon saving:

![gmedit1](https://user-images.githubusercontent.com/23438866/37379834-6efb8af4-272d-11e8-8908-f675d8981b58.png)
===
When I add second star `/** */` editor let me save the file without error. However as you can see below, it doesn't work properly (at least for GMS1). When not using coroutines multi line comments works fine, if that matters.

![image](https://user-images.githubusercontent.com/23438866/37379893-d00ceae0-272d-11e8-8ccc-cdd72b103bfd.png)

**Comment by YellowAfterlife** [comment]
Fixed for the next version - `*\/` is what's supposed to happen (as otherwise you'd be closing that comment containing the actual code but it wasn't being handled properly on actual "compiler" side of things.
