### ISSUE TITLE
Bug: statusbar argument helper

### ISSUE THREAD

**Issue by maciekr1234** [GameMakerDiscord/GMEdit#17]
When writing array with index as argument to any function or script, the argument highlight in statusbar doesn't update to cursor position.

![bez tytulu](https://user-images.githubusercontent.com/23438866/37440389-62679d9c-27f4-11e8-999c-c0e54ccdd9cd.png)

**Comment by YellowAfterlife** [comment]
This is supposedly the longest-standing bug, dating back to original web version of GMLive. The thing is that this has to be very fast (check is executed whenever cursor position changes) so it has to be token-based (looking from cursor position backwards), but there's a bit of complexity in deciding what is the actual function call this way.

**Comment by YellowAfterlife** [comment]
Fixed for the next version.
