### ISSUE TITLE
Error building on mac

### ISSUE THREAD

**Issue by christopherwk210** [GameMakerDiscord/GMEdit#2]
After installing the latest version of Haxe, cloning the project, and including the latest Electron binary & included files, I run the following:

```
$ haxe -cp src -js ./bin/resources/app/app.js -D nodejs -main Main -dce full
```

And this outputs:

```
src/ui/GlobalLookup.hx:2: characters 7-18 : Type not found : haxe.ds.Map
src/ui/KeyboardShortcuts.hx:22: lines 22-281 : Defined in this class
src/Main.hx:92: characters 2-19 : Class<ui.GlobalLookup> has no field init
```

This is on macOS Sierra 10.12.6 (16G1036)

**Comment by YellowAfterlife** [comment]
I've been using a beta of Haxe 4 for this (which moved a few standard library classes around), but that one is not actually used at all - can safely remove that line (also comitted https://github.com/GameMakerDiscord/GMEdit/commit/3d4b79ac4ff756ad6965a38502f6f3d146b9b094)

**Comment by christopherwk210** [comment]
Just pulled and tried to rebuild, that fixed it. Thanks!
