### ISSUE TITLE
Sometimes, GMEdit saves scripts with "scripts/" before their names

### ISSUE THREAD

**Issue by 9Morello** [GameMakerDiscord/GMEdit#20]
Unfortunately, I haven't found a way to consistently replicate this yet.
Sometimes, after saving a script in GMEdit, it appears in GM:Studio 1.4 as "`scripts/script_actual_name.gml`". You can just edit the script name in the GM:Studio back to `script_actual_name.gml` and it works again.

**Comment by YellowAfterlife** [comment]
Fortunately or unfortunately, this has nothing to do with GMEdit - it never modifies the project file (which is what defines script names and paths). Enabling source control for a project seems to fix this ([see here](https://itch.io/t/198871/the-editor-doesnt-update-my-gms-scripts-anymore)).

**Comment by 9Morello** [comment]
Oh, really? Since this only happened when saving a script using GMEditor, I immediately thought it was at fault.  Enabling GM's own source control seems to make it watch for changed files, it seems.

Thanks for the fast reply, I'll close the issue.

**Comment by 9Morello** [comment]
Just got the same issue after enabling source control in the IDE. Any idea on what could be the culprit, @YellowAfterlife ?

**Comment by YellowAfterlife** [comment]
You could try disabling "backup on save" / "backup on run" in GMS preferences, which seem to cause some oddities, but other than that I don't have any specific advice on this - I've only had this issue (script name becoming corrupt or one script reference being replaced by other) a few times, most of which it were prior to starting GMEdit's development as such.

**Comment by 9Morello** [comment]
Ok, guess I'll just have to deal with it. Weird GM bug. Thanks for the help!
