### ISSUE TITLE
Issues when adding macro

### ISSUE THREAD

**Issue by maciekr1234** [GameMakerDiscord/GMEdit#21]
When new macro is created, you need to close and reopen application in order to changes take effect. Even reloading the app window (Ctr+Shift+F5) doesn't solve it, only physically closing and opening it again works.

**Comment by YellowAfterlife** [comment]
For GMS1 or GMS2? Ctrl+R should be re-checking the project files for new items.

**Comment by maciekr1234** [comment]
I haven't noticed before that Ctrl+R works ! Sorry about that but I'm not sure if I did try that actually or it might happened in any of the previous versions. Since then when I edit macros i hit save and exit the program. 
I have tried Ctrl+R now, it's working. Sorry :)
