### ISSUE TITLE
Suggestion: compatibility with Ace color themes

### ISSUE THREAD

**Issue by 9Morello** [GameMakerDiscord/GMEdit#22]
Is it possible to make it compatible with Ace themes out of the box? As in, to be able to take [this file](https://github.com/ajaxorg/ace/blob/master/lib/ace/theme/solarized_light.css), put it inside GMEditor and have the color scheme applied work without having to manually edit the .css files.

**Comment by maciekr1234** [comment]
Personally I think it's not worth wasting time to figure out the way to accept both types of theme, instead of developing new features or fixing bugs. In my opinion you could easily convert the theme with a little knowledge of css. Anyway Ace's themes probably wouldn't be working without adding special syntax selectors rules such as `.ace_scriptname` or `.ace_globalvar`.

**Comment by YellowAfterlife** [comment]
I have originally attempted to include Ace style classes for tokens but quickly realized that this is very hard to do in a way that makes sense.

So, for example, with variables Ace themes have `.ace_variable` (user-defined) or `.ace_variable.ace_language` (built-in) while GMEdit's GML highlighter differentiates between `var`, instance variables, `global.*`, `globalvar`, extension variables, and built-in variables (be that instance-specific or global). And most Ace themes don't assign a different color to `.ace_variable.ace_language` so all variables would look the same unless offloading some of these types onto different classes.

Still, if you feel like you could find a way to map these, you could make a tool to do a automatically convert themes - Ace themes are written in very standard CSS so it'd be largely a find-replace job once you decide the most adequate match for each class. Would still require manual tweaking to not be inferior to default theme though.

**Comment by 9Morello** [comment]
Honestly, with the new theme tools, I don't think this is worth the trouble anymore.
