### ISSUE TITLE
Type magic isn't work without #import something in code

### ISSUE THREAD

**Issue by alsekond** [GameMakerDiscord/GMEdit#25]
Code below will not transform on save
enum Vec2 {x,y,sizeof}
var v:Vec2 = Vec2();

Code below will transform on save
#import blank.* as Blank
enum Vec2 {x,y,sizeof}
var v:Vec2 = Vec2();

**Comment by YellowAfterlife** [comment]
Hm, indeed - `#import` preprocessor avoids going over the code if it doesn't look like it has imports but for type things it can't tell that easily.

Adding a "global" import file to the project (even if blank) would have it check everything regardless.

I'll add a separate option for this in the next version.

**Comment by YellowAfterlife** [comment]
Fixed for the next version.
