### ISSUE TITLE
#gmcr magic will not work if using break to finish while

### ISSUE THREAD

**Issue by alsekond** [GameMakerDiscord/GMEdit#26]
Don't know, may be it's better to add break to limitations section

script below will not end because break stops switch block in translated code instead of while
#gmcr
#args map
var key = ds_map_find_first(map);
while true
{
    if is_undefined(key) then break;
    yield [key,map[? key]];
    key = ds_map_find_next(map,key);
}

script below will work good without break
#gmcr
#args map
var key = ds_map_find_first(map);
while not is_undefined(key)
{
    yield [key,map[? key]];
    key = ds_map_find_next(map,key);
}

**Comment by YellowAfterlife** [comment]
Fixed for the next version.
