### ISSUE TITLE
Type magic property auto-completion won't appear if there's a longer variable than one typed

### ISSUE THREAD

**Issue by alsekond** [GameMakerDiscord/GMEdit#28]
I print variable name then print dot (properties don't appear) backspace dot and print it again (properties appear)
Please check short video on this
http://take.ms/dDROo

**Comment by YellowAfterlife** [comment]
Replication:
```
#import ds_map.* in Map
var maps, map;
¦
```
and type "map." - since the auto-completion menu is still up as of writing `.`, it doesn't reappear on time.
