### ISSUE TITLE
script coloring feature

### ISSUE THREAD

**Issue by alsekond** [GameMakerDiscord/GMEdit#31]
it is possible to customize color for scripts in GMS2. It is good feature because you can see a difference between gml functions and scripts. Is it possible to add this feature in gmedit?

**Comment by YellowAfterlife** [comment]
GMEdit is styled using CSS themes.

For example, you can make a copy of `resources/app/themes/gms2`, name it `dark+`, change the contents of gms2.css to be just
```css
#main .gml .ace_script {
	color: red;
}
```
then set it via Preferences (may require restarting GMEdit), and that's it
![image](https://user-images.githubusercontent.com/731492/43209591-b5ba167e-9035-11e8-80dd-9e2e789e8f2c.png)

CSS classes for code editor elements can be viewed by doing Ctrl+Shift+I and then
```js
aceEditor.debugShowToken()
```
in the Console tab.
