### ISSUE TITLE
Creating new events sometimes puts an "undefined" in GMS2 code

### ISSUE THREAD

**Issue by sanboxrunner** [GameMakerDiscord/GMEdit#38]
![image](https://user-images.githubusercontent.com/31973761/47956543-44eb2500-df7c-11e8-9994-ace0fdd58e56.png)

See the "undefined" in code there.

If I keep adding blank events, I will keep getting an "undefined" in code.

Thanks Vadim! I was checking out how GMEdit has users creating events and noticed this

**Comment by YellowAfterlife** [comment]
Are you using the git version or slightly older public release? As I had fixed [something related to that earlier](https://github.com/GameMakerDiscord/GMEdit/commit/ce52c42fb40633efbf4e833864c8468c2a68f68a).

**Comment by sanboxrunner** [comment]
Public release, and looking at that, I'd say that's definitely the fix. I'll close! Thanks Vadim!
