### ISSUE TITLE
Inline code in HTML5 not work with script_execute

### ISSUE THREAD

**Issue by alsekond** [GameMakerDiscord/GMEdit#39]
In GMS2 it seems isn't work script_execute for scripts defined in extensions for HTML5 target.

[gmedit_inline_test.zip](https://github.com/GameMakerDiscord/GMEdit/files/2551672/gmedit_inline_test.zip)

**Comment by alsekond** [comment]
included project prints to output 4 strings:
trace execute
trace scirpt_execute
test execute
test script execute

trace defined as common script
test defined using #lamdef

In Windows target this script works good.
In HTML5 target throws an error after 3 line in console

**Comment by YellowAfterlife** [comment]
I thought this was fixed, filed to bugtracker https://bugs.yoyogames.com/view.php?id=30168

**Comment by YellowAfterlife** [comment]
This is finally fixed as of GMS 2.2.2
