### ISSUE TITLE
Ability to have control over root layout.

### ISSUE THREAD

**Issue by Shadowblitz16** [GameMakerDiscord/GMEdit#41]
Please allow the ability to have complete control over root project folders and folder names.
this would work similarly to how custom views work in gamemaker studio 2 but it would be for the default view.

**Comment by YellowAfterlife** [comment]
I'm fairly confident that renaming top-level directories can cause something to go wrong so you are free to experiment (safety checks are [here](https://github.com/GameMakerDiscord/GMEdit/blob/master/src/ui/treeview/TreeViewItemMenus.hx#L52-L64)) and report back on whether this causes GMS2 to corrupt your project or not
