### ISSUE TITLE
rename or make alias for #gmcr as #function(paramaters..) or #coroutine(paramaters..)

### ISSUE THREAD

**Issue by Shadowblitz16** [GameMakerDiscord/GMEdit#43]
#gmcr may not clear to what its supposed to be even though I know it mean game maker co routine
I suggest making a alias called coroutine, function or script which allows for passing in parameters.

script would probably be better, as so someone can define scripts as..
```    
script (arg0, arg1, arg2)
{
    
}

//or

#script (arg0, arg1, arg2)
{
    
}

**Comment by YellowAfterlife** [comment]
`#gmcr` stands for GameMaker CoRoutines, same as the [web tool](https://yal.cc/r/gmcr/).

It has no obligation to make sense as the user is expected to read [the wiki page](https://github.com/GameMakerDiscord/GMEdit/wiki/Using-%23gmcr-magic) prior to using it.

Speaking of which, the proposed syntax is not how it works - `#gmcr` marks the containing script as a coroutine - it does not create coroutines inside other scripts, so the proposed syntax makes no sense.
