### ISSUE TITLE
Lambda detection doesn't work if the opening bracer is in the next line

### ISSUE THREAD

**Issue by 9Morello** [GameMakerDiscord/GMEdit#50]
```
#lambda test(arg) {
}
```
works, but
```
#lambda test(arg) 
{
}
```
throws an error, saying it can't process it and it was expecting a {code} or (args). In addition, the code below also throws an error, saying it expects an argument name (probably because of the bracers):
```
#lambda test() {
}
```

**Comment by YellowAfterlife** [comment]
`#lambda` is relatively restrictive because I was aiming for syntax that would look the same when loading it back (e.g. number of spaces between `#lambda` and `test` is preserved).

Ideally I would support both that and Haxe-style `func(#lambda return ...)`, but this demands some rewriting to its post-processor.

**Comment by 9Morello** [comment]
Seems like adding a lambda and removing it later doesn't remove the code from the placeholder extension. Is that intentional?

**Comment by YellowAfterlife** [comment]
If your remove the definition from GMEdit, it will remove the definition from the extension. If you remove the resource itself or via GM, it will not.

**Comment by 9Morello** [comment]
@YellowAfterlife I actually removed them using GMEdit (as in, the #lambda definition inside the script, not from the extension itself). I only noticed the functions were still there (inside the extension) later on, when YYC complained about an uninitialized variable in a function from the placeholder extension.
Version is GMS1, using GMEdit compiled in 29/03. If there's any other info it might be useful, just tell.

**Comment by YellowAfterlife** [comment]
I tested this just now and it does remove the definitions from the extensions.

What likely happened to you is having done some changes in IDE during the same session and thus causing it to overwrite the extension with an older version that it cached in memory.

As I had previously mentioned, there's not much that GMEdit can do about GMS1 IDE being extremely bad with external changes.

**Comment by 9Morello** [comment]
I see, thanks for the clarification.

**Comment by YellowAfterlife** [comment]
Fixed in https://github.com/GameMakerDiscord/GMEdit/commit/c16d4a5385f12a00efd67a47faae19de2986c5fd

**Comment by 9Morello** [comment]
Nice, thanks for the fix!
