### ISSUE TITLE
Type magic is non-functional in RoomCC code

### ISSUE THREAD

**Issue by nommiin** [GameMakerDiscord/GMEdit#52]
Type magic does not function and is not recognized in `file_kind_yy_KYyRoomCCs`

**In GMEdit**
![image](https://user-images.githubusercontent.com/6483989/55346789-ebc6e500-5478-11e9-9a29-61e5aaf80850.png)

**In GMS 2**
![image](https://user-images.githubusercontent.com/6483989/55346952-46f8d780-5479-11e9-8b97-74e4fb66136f.png)

**Comment by YellowAfterlife** [comment]
Fixed with https://github.com/GameMakerDiscord/GMEdit/commit/af4a5f30b1124783362d495c9048c723089125b4
