### ISSUE TITLE
Block scoped variables inside of case "blocks"

### ISSUE THREAD

**Issue by AndrewBGM** [GameMakerDiscord/GMEdit#60]
The "block scoped var" linting rule doesn't seem to work inside of switch/case blocks unless you explicitly add braces around the contents of each case.  I can see why this would be working this way, but it would be very nice if GMEdit would detect case blocks as actual blocks.

[Example](https://i.imgur.com/RTz0iDb.png)

**Comment by YellowAfterlife** [comment]
Added an option for this 
![image](https://user-images.githubusercontent.com/731492/66223735-ddce7700-e6dc-11e9-9d62-28f188b50ace.png)
