### ISSUE TITLE
Automatic JSDoc types for #args magic

### ISSUE THREAD

**Issue by glitchroy** [GameMakerDiscord/GMEdit#62]
Given the #args magic:
```gml
#args _my_var:MyType
```
it would be neat for the generated JSDoc to look like this
```gml
/// @param {MyType} _my_var
```

The changelog for the newest beta from 2019-10-02 does read `JSDoc now supports {type} syntax`, however when I add the type manually, it gets reset every time.

**Comment by YellowAfterlife** [comment]
To note further, if you only intend to use GMEdit, you don't need JSDocs much at all - GMEdit beta can auto-derive argument names and types from source code in majority of cases.
