### ISSUE TITLE
Preferences don't show the dialect directory :(

### ISSUE THREAD

**Issue by Puuuul-cmd** [GameMakerDiscord/GMEdit#65]
Hello,

I followed the Rivals guide to get started for the steam workshop, so one step is to extract the rivals dialect to the folder, however when I open my preferences there is no such part at the bottom as you describe it in your wiki

please respond ASAP

Sincerely,

Puuuul

**Comment by YellowAfterlife** [comment]
You need to install the beta version

**Comment by Puuuul-cmd** [comment]
Thanks a lot!
