### ISSUE TITLE
Add "infinity" constant

### ISSUE THREAD

**Issue by xDGameStudios** [GameMakerDiscord/GMEdit#68]
Infinity constant doesn't highlight like other constants. (I'm on Mac OSX how can I keep up to the last version of the program?)

**Comment by YellowAfterlife** [comment]
You can copy the "fnames" file from GMS2 runtime directory to GMEdit directory (app/api/v2). I do so time to time for releases

You can keep GMEdit up to date by installing the itch.io app https://itch.io/app

**Comment by xDGameStudios** [comment]
Okay! Thank you, btw.. is there lint error and warning reports for files in extensions category of GMEdit.. for example for missing ";" at the end of statements or for "=" comparison instead of "=="?!

**Comment by YellowAfterlife** [comment]
If you open an extension file inside GMEdit (by clicking it under the extension "folder"), it will show you the lint warnings for it.

**Comment by xDGameStudios** [comment]
I only get lint errors (not warnings) @YellowAfterlife

**Comment by YellowAfterlife** [comment]
Test with a missing function, check what you've configured for linting in Project Properties or Preferences.
