### ISSUE TITLE
Make GMEdit able to edit every property of an object

### ISSUE THREAD

**Issue by brockuniera** [GameMakerDiscord/GMEdit#72]
Feature Request: Objects have a lot of properties like Persistent, Visible, Solid, Parent, etc. Most of these can be set in the creation code but it would be nice to be able to view and set these directly from GMEdit instead of switching back to GMS or writing full on code. There's been more than a few times I've had to tab out of beautiful GMEdit to find the parent of an object I'm editing with the super slow searching in GMS. Thanks!

**Comment by YellowAfterlife** [comment]
You can, but only for GMS2 - that's what "properties" meta-event is for.
