### ISSUE TITLE
CLI Interface

### ISSUE THREAD

**Issue by ColtonPhillips** [GameMakerDiscord/GMEdit#74]
When I try to open a project (whether open in gms2 or not) 
from the cli like,

./temp/Editor.exe proj/proj.yyp

it seems like it tries to open the project, but doesn't successfully do it. 
I'd like to automate the editor opening, to reduce keystroke fatigue... Any chance this is an easy fixerino?

**Comment by YellowAfterlife** [comment]
CLI definitely works but you'll need an absolute path to YYP - not sure what the working directory is with Electron.

**Comment by ColtonPhillips** [comment]
OH! OK thanks. I'll close the issue i'm sure you have bigger fish to fry. THanks!
