### ISSUE TITLE
New bare bones project | Mac OSX | Can't update YY: Expected a GUID instead 'sprite_index = "[object Object]"; // amiss'

### ISSUE THREAD

**Issue by Mattykins** [GameMakerDiscord/GMEdit#77]
Hello!

Please forgive the lack of information I'm really new to GameMaker. I'm on Mac OSX, I made a bare bones project with 1 object with a single Step event, and when I attempt to open up the object and make edits, I receive the following error upon trying to Save:

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/1888352/91682149-7051e300-eb05-11ea-9d0e-f8eba3d4218b.png">

It appears to be due to the sprite_index var "[object Object]"  string where it expects a GUID. 

Happy to provide any additional information that may be necessary.

**Comment by YellowAfterlife** [comment]
- What GameMaker version are you using?
- Does using a beta build of GMEdit change anything?

**Comment by Mattykins** [comment]
Using the MacOSX beta build found on Itch it works perfectly! Sorry, I should've tried that in the first place. Here's the GameMaker version info in case that is still helpful.

![image](https://user-images.githubusercontent.com/1888352/91741830-20f1ce00-eb6a-11ea-890c-963e86e14d38.png)
