### ISSUE TITLE
Support for 64 Bit Architecture?

### ISSUE THREAD

**Issue by Grub0** [GameMakerDiscord/GMEdit#78]
Hello, 

I was wondering if there was a way I could build the plugin so that it would support 64 bit architecture. I recently implemented this into a GMS2 project and it seems to work fine on Windows, but when we run the project on MacOS we get errors in the overlay, and when we submitted to GOG they gave us back the following message: 

As for the integration, here are detailed information:
Game is using third party extension for GameMaker (GOG.gml - https://yellowafterlife.itch.io/gog-gml) that is responsible for wrapping and handling our integration calls.

However, when we run the game through terminal, many errors like the ones visible below can be found in the game's log:

error trying to load /Applications/zzz_Galaxy_Games//Contents/Resources/gog.gml.dylib - dlopen(/Applications/zzz_Galaxy_Games/Contents/Resources/gog.gml.dylib, 1): no suitable image found.  Did find:
	/Applications/zzz_Galaxy_GamesContents/Resources/gog.gml.dylib: mach-o, but wrong architecture
	/Applications/zzz_Galaxy_Games/Contents/Resources/gog.gml.dylib: mach-o, but wrong architecture
error trying to load /Applications/zzz_Galaxy_Games/Contents/Resources/gog.gml.dylib - dlopen(/Applications/zzz_Galaxy_Games/Contents/Resources/gog.gml.dylib, 1): no suitable image found.  Did find:
	/Applications/zzz_Galaxy_Games/Contents/Resources/gog.gml.dylib: mach-o, but wrong architecture
	/Applications/zzz_Galaxy_Games/Contents/Resources/gog.gml.dylib: mach-o, but wrong architecture
error trying to load @loader_path/libGOG.gml.dylib - dlopen(@loader_path/libGOG.gml.dylib, 1): image not found
Full log is attached.

Above errors are caused by incompatibility between game itself and included library for that extension:

Game itself is 64-bit.
Mac_Runner: Mach-O 64-bit executable x86_64
But "gog.gml.dylib" located in "/Contents/Resources/" is 32-bit only.
gog.gml.dylib: Mach-O dynamically linked shared library i386
In order to work, "gog.gml.dylib" included in the build has to support 64-bit architecture.

I apologize if this is something I could easily do on my own, but I'm wondering if this is something already supported by the plugin if I just use different settings when building from visual studio, or if changes would need to be made? When I try to build w/ VS 2019 I get a number of errors even when targeting x86 as it states in the documentation. 

Thanks,
-Rob Clifford

**Comment by YellowAfterlife** [comment]
Was this meant to be filed under https://github.com/GameMakerDiscord/GOG.gml ?

You'll want to remove `-m32` from build_osx.sh and recompile the extension yourself.

Since Mac development is a mild nightmare, I usually only get around to it when someone pays me to do so as part of porting work.

**Comment by Grub0** [comment]
Yes I did mean for it to be on that repo, that's my bad I had multiple tabs open. Thanks for the guidance, yeah I agree Mac development is a garbage fire, but hopefully I can get this working without too much issue. I'll let you know how it works out, you can feel free to close out the issue.

**Comment by YellowAfterlife** [comment]
If you get stuck, re-file the issue under GOG.gml repository so that I know to check it next time I do something with it.
