### ISSUE TITLE
AUR (Arch User Repository) Package

### ISSUE THREAD

**Issue by CrankySupertoon** [GameMakerDiscord/GMEdit#79]
https://aur.archlinux.org/packages/gmedit-bin/

**Comment by YellowAfterlife** [comment]
I'm as of yet uncertain as to what I am expected to do with this information

**Comment by CrankySupertoon** [comment]
Its a AUR Package. If you are familar with Ubuntu PPA's think of it as the same concept instead of every project having a different PPA its one master repo.

**Comment by CrankySupertoon** [comment]
Also i had to mirror the download since itch does not provide direct links. If you want to upload them additionally to github releases feel free too.

**Comment by CrankySupertoon** [comment]
https://cdn.crankysupertoon.live/dist/gmedit-editor-linux.zip

**Comment by YellowAfterlife** [comment]
I figured that much - I meant in terms of what action(s) I was expected to take as the result of this.

I have now added GitHub release pushing to the build script. Betas are marked are pre-releases while non-betas aren't.
