### ISSUE TITLE
Static method "@hint" is not showing arguments in status bar

### ISSUE THREAD

**Issue by KeeVeeGames** [GameMakerDiscord/GMEdit#83]
![electron_SD4dTU9Asr](https://user-images.githubusercontent.com/10993317/97212771-e30fcf80-17d1-11eb-9620-a1ccc3c6aafd.png)
![SourceTree_ntnszL6w4J](https://user-images.githubusercontent.com/10993317/97212799-eb680a80-17d1-11eb-97a2-5d19a8d465da.png)
![electron_AcIvJehNaA](https://user-images.githubusercontent.com/10993317/97212804-ec993780-17d1-11eb-9e05-35942e5f4b0e.png)

**Comment by YellowAfterlife** [comment]
Fixed in 6efdbf02aaa5c1a7d2ff98858bcffd3159f68259
