### ISSUE TITLE
Add an option to @hint constructors

### ISSUE THREAD

**Issue by KeeVeeGames** [GameMakerDiscord/GMEdit#84]
This doesn't work:
![image](https://user-images.githubusercontent.com/10993317/99885253-a609f200-2c44-11eb-9717-d3e92a4d17d4.png)

**Comment by YellowAfterlife** [comment]
Fixed in 99739d71304f68edc62b69663135352562e28b3d - can now do
```
/// @hint Type(a, b)
```
for
```js
new Type(¦)
````
and
```js
/// @hint Type:(a, b)
```
for
```js
var me:Type;
me(¦);
```
