### ISSUE TITLE
[feature request] Add support for @private JSDoc

### ISSUE THREAD

**Issue by adam-coster** [GameMakerDiscord/GMEdit#88]
Since GameMaker structs don't have a concept of "private", the best we can do is use a naming convention (like an underscore prefix) to indicate that programmers shouldn't touch those fields. Even better would be if GMEdit allowed marking struct parameters (including functions) as private, using the JSDoc `@private` keyword, and then didn't include such parameters in autocomplete contexts.

**Comment by YellowAfterlife** [comment]
I can probably add `@private`; for naming convention approach, there is "Regex for determining that 2.3 struct variables are private (e.g. `^_` for anything starting with an underscore)" in Project Properties.

**Comment by adam-coster** [comment]
Oooooh, perfect. I'll take advantage of that then instead!
