### ISSUE TITLE
Hang on Loading Removed Projects

### ISSUE THREAD

**Issue by Atrusario** [GameMakerDiscord/GMEdit#9]
When attempting to load recent projects that have been removed, the loading text appears and remains into eternity. When opened, the editor should account for each project saved in resents, and remove those rendered inaccessible, or at least provide an error message when attempting to load an inaccessible project.

**Comment by YellowAfterlife** [comment]
Fixed for the next update - now marks missing projects and shows a notice if trying to open them.
